export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SIGN_UP = "SIGN_UP";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const INPUT_CHANGE = "INPUT_CHANGE";
export const CLEAR_ALL_INPUTS = "CLEAR_ALL_INPUTS";

export const SUBMIT_SOLUTION = "SUBMIT_SOLUTION";
export const CLEAR_PROMPT = "CLEAR_PROMPT";

export const GET_LEADERBOARD = "GET_LEADERBOARD";
export const CHANGE_SCOREBOARD = "CHANGE_SCOREBOARD";
export const CLEAR_SCOREBOARD = "CLEAR_SCOREBOARD";

export const CHANGE_ROOM = "CHANGE_ROOM";
export const GET_PROMPT = "GET_PROMPT";
export const SET_COMPLETE = "SET_COMPLETE";

export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const GET_ONLINE_USER = "GET_ONLINE_USER";

export const USER_SUBMITION = "USER_SUBMITION";
export const SOLUTION_CHANGE = "SOLUTION_CHANGE";

export const TIMER_CHANGE = "TIMER_CHANGE";
