export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const SIGN_UP = 'SIGN_UP'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const INPUT_CHANGE = 'INPUT_CHANGE'
export const CLEAR_ALL_INPUTS = 'CLEAR_ALL_INPUTS'

export const SUBMIT_SOLUTION = 'SUBMIT_SOLUTION'
export const CLEAR_PROMPT = 'CLEAR_PROMPT'

export const GET_LEADERBOARD = 'GET_LEADERBOARD'
export const CHANGE_SCOREBOARD = 'CHANGE_SCOREBOARD'
export const CLEAR_SCOREBOARD = 'CLEAR_SCOREBOARD'

export const CHANGE_ROOM = 'CHANGE_ROOM'
export const GET_PROMPT = 'GET_PROMPT'
export const SET_COMPLETE = 'SET_COMPLETE'

export const SET_ONLINE_USER = 'SET_ONLINE_USER'
export const SET_OFFLINE_USER = 'SET_OFFLINE_USER'
export const INIT_ONLINE_USERS = 'INIT_ONLINE_USERS'