export const OPEN_MODAL = "OPEN_MODAL";
export const CLOSE_MODAL = "CLOSE_MODAL";
export const SIGN_UP = "SIGN_UP";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const INPUT_CHANGE = "INPUT_CHANGE";
export const CLEAR_ALL_INPUTS = "CLEAR_ALL_INPUTS";

export const SUBMIT_SOLUTION = "SUBMIT_SOLUTION";
export const CLEAR_PROMPT = "CLEAR_PROMPT";

export const GET_DAILY_LEADERBOARD = "GET_DAILY_LEADERBOARD";
export const GET_LEADERBOARD = "GET_LEADERBOARD";
export const CHANGE_SCOREBOARD = "CHANGE_SCOREBOARD";
export const CLEAR_SCOREBOARD = "CLEAR_SCOREBOARD";

export const CHANGE_ROOM = "CHANGE_ROOM";
export const GET_PROMPT = "GET_PROMPT";
export const SET_COMPLETE = "SET_COMPLETE";

export const SET_ONLINE_USERS = "SET_ONLINE_USERS";
export const GET_ONLINE_USER = "GET_ONLINE_USER";

export const USER_SUBMITION = "USER_SUBMITION";
export const SOLUTION_CHANGE = "SOLUTION_CHANGE";

export const TIMER_CHANGE = "TIMER_CHANGE";
export const RESET_TIMER = "RESET_TIMER";
export const RESET_RESULTS = "RESET_RESULTS";

export const GET_PROMPT_DUEL = "GET_PROMPT_DUEL";
export const SUBMIT_SOLUTION_DUEL = "SUBMIT_SOLUTION_DUEL";
export const RESET_RESULTS_DUEL = "RESET_RESULTS_DUEL"
export const PLAYER_JOINED_DUEL = "PLAYER_JOINED_DUEL"
export const DUEL_SOLUTION_CHANGE = "DUEL_SOLUTION_CHANGE"
export const PLAYER_TYPING = "PLAYER_TYPING"
export const OPPONENT_RESULTS = "OPPONENT_RESULTS"
export const SET_CONSOLE_RESULTS = "SET_CONSOLE_RESULTS"
export const RESET_CONSOLE_RESULTS = "RESET_CONSOLE_RESULTS"
export const CLEAR_OPPONENT_CONSOLE = "CLEAR_OPPONENT_CONSOLE"
export const CLEAR_DUEL_PROMPT = "CLEAR_DUEL_PROMPT"
export const SET_DUEL_ROOM = "SET_DUEL_ROOM"
export const SET_DUEL_COMPLETE = "SET_DUEL_COMPLETE"
export const CLEAR_OPPONENT_PROMPT = "CLEAR_OPPONENT_PROMPT"